[package]
name = "rustmap"
version = "0.1.0"
authors = ["Nadir Sampaoli <nadirsampaoli@gmail.com>"]

[dependencies]
toml = "*"
serde = "^1"
serde_derive = "^1"
gtk = { version = "^0.3", features = ["v3_22"] }
gdk = "^0.7"
gdk-pixbuf = "^0.3"
cairo-rs = "^0.3"
